parameters:
    se.locale_manager.class: SymfonyExtraBundle\Locale\LocaleManager
    se.twig.extensions.locale.class: SymfonyExtraBundle\Twig\LocaleExtension
    se.twig.extensions.paginator.class: SymfonyExtraBundle\Twig\PaginatorExtension

services:
    swiftmailer.mailer.transport.file:
        class: SymfonyExtraBundle\SwiftmailerExtension\Transport\FileTransport
        arguments: ["@swiftmailer.mailer.default.transport.eventdispatcher", "%mailer_local_dir%"]

    swiftmailer.mailer.transport.mandrill:
        class: SymfonyExtraBundle\SwiftmailerExtension\Transport\MandrillTransport
        arguments: ["@swiftmailer.mailer.default.transport.eventdispatcher", "@kernel"]

    swiftmailer.mailer.plugin.csstoinline:
        class: SymfonyExtraBundle\SwiftmailerExtension\Plugin\CssToInlinePlugin
        arguments: ["@assetic.asset_manager", "@assetic.filter_manager", "@kernel"]
        tags:
            - { name: swiftmailer.default.plugin }

    se_locale_manager:
        class: "%se.locale_manager.class%"
        arguments: ["%locale%", "%locales%", "@request"]
        scope: request

    se.twig.extensions.locale:
        class: "%se.twig.extensions.locale.class%"
        tags:
            - { name: twig.extension }

    se.twig.extensions.paginator:
        class: "%se.twig.extensions.paginator.class%"
        tags:
            - { name: twig.extension }